"""Dump the actual Cypher generated by tmpl_parser for AB.MS.GRP.1
under both the legacy (per_primary=false) and v11 (per_primary=true,
sample-with-replacement) paths so we can EXPLAIN/PROFILE them by hand."""
import json, sys, pathlib
sys.path.insert(0, "tmpl_gen/src")
from tmpl_gen.tmpl_parser import TmplGenNeo4j  # type: ignore

REPO = pathlib.Path(".").resolve()
DBCONF = REPO / "tmpl_gen" / "data_generation" / "neo4j-local-config.json"
TMPL_JSON = REPO / "_v11_build" / "_anchor_fix_test" / "ab_ms_grp1.json"

BASE_GENCFG = {"version": "0.0", "default_propname": "name",
               "default_count_limit": 10, "default_order_by": "none",
               "override_order_by": "random", "list_property_separator": ", ",
               "verbose": 1}

# write temp gencfg files (TmplGenNeo4j wants a path)
import tempfile
def _write(d):
    fd, p = tempfile.mkstemp(suffix=".json")
    pathlib.Path(p).write_text(json.dumps(d))
    return p

cfg_legacy_path = _write(BASE_GENCFG)
cfg_v11 = dict(BASE_GENCFG); cfg_v11["per_primary_grouping"] = True; cfg_v11["allow_nullprops"] = True
cfg_v11_path = _write(cfg_v11)

tmpls  = json.loads(TMPL_JSON.read_text())
print(f"Loaded {len(tmpls)} templates from {TMPL_JSON.name}")

for label, gpath in [("LEGACY (per_primary=false)", cfg_legacy_path),
                     ("V11    (per_primary=true)",  cfg_v11_path)]:
    print(f"\n========== {label} ==========")
    opts = {"gen_conf_file": gpath, "neo4j_conf_file": str(DBCONF), "count_max": 1500}
    obj = TmplGenNeo4j(opts)
    obj.options["count_max"] = 1500
    for tobj in tmpls:
        captured = {"queries": []}
        orig = obj.neo4j_driver.run_query_collect
        def fake(q, timeout=None, _capt=captured):
            _capt["queries"].append(q)
            raise SystemExit("captured")
        obj.neo4j_driver.run_query_collect = fake
        try:
            obj.process_template(tobj)
        except SystemExit:
            pass
        finally:
            obj.neo4j_driver.run_query_collect = orig
        for i, q in enumerate(captured["queries"]):
            print(f"\n--- query #{i} ---")
            print(q)
    obj.neo4j_driver.close()
