# Runs scripts/iftgen.py ($IFTGEN_PY) on $TMPL_FILE
# generate triples in directory $RESULTS_DIR

# CUSTOMIZE AS NEEDED

# Python script that generates triples:
IFTGEN_PY="../scripts/iftgen.py"

# generation configuration parameters.
GENCONF="gencfg_default_neo4j.json"

# neo4j connection and DB parameters: URL, USER, PASSWORD, DB:
NEO4JCONF="neo4j-local-config.json"

# output + results directory name:
RESULTS_DIR="results-dir"

RESULTS_DIR_WITH_PROPS="results-dir"

# Next are two files generated by the create-test-tmpl.py program or
# the make-test-templates.sh script:

# test template JSON file for nodes + relationships:
TMPL_FILE="test-templates.json"

# UNCOMMENT NEXT LINE TO USE THE LARGE TEST WITH 1 template/property INSTEAD
#        OF 1 template/node
TMPL_FILE=${TMPL_FILE/.json/+props.json}

# directory where the triples and the results summary file are saved:
# **** CAUTION: results directory will be erased and recreated:
RESULTS_DIR="results_test_triples"
echo "**** CAUTION: results directory ${RESULTS_DIR} will be erased and recreated"
rm -rfv ${RESULTS_DIR}

# create max. 10 triples per template; it's just a test:
COUNT_MAX=10

# run python script to create triples from templates in given file, using conf. files:
python3 $IFTGEN_PY --cmd generate --genconf $GENCONF \
        --dbconf $NEO4JCONF --tmpl $TMPL_FILE \
        --results_dir $RESULTS_DIR --count_max $COUNT_MAX

echo
echo "==========================================================="
echo "Triple generation results in file ${RESULTS_DIR}/_results-report.json"
echo "Examine the ""results"" dictionary and look for entries with generated_count==0 or with ""exception"" fields."
echo
echo "All triples generated are in the ${RESULTS_DIR} directory/"
